import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Instagram Threads",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./fonts/insta-sans.ttf",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  );
}
